[filenames, path_pkgdata] =  get_reaction_time_filenames();
path_fitdata = "~/ondrive/analysisDG/PBups_trialhistory/analyze_reaction_time/saved_fits/";

filenames = "sess_rawdata_X017.mat";

figure()
markersize = 12;
c_postright = get_linear_cmap([0 164 204]./255, 10);
c_postleft = get_linear_cmap([233 115 141]./255, 10);
c_pR = c_postright(1,:);
c_pL = c_postleft(1,:);

for i = 1:length(filenames)
    
    display(filenames{i});
    data = load([path_pkgdata, filenames{i}]);
    fitdata = load(strcat(path_fitdata, filenames{i}(1:end-4), "_goright_earlate.mat"));
    fit_pokedR = fitdata.pred_choices(:,10);
    
    h(i) = subplot(2,3,i); hold on;
    
    % compute PC conditioned psychometric curves
    rc = pbups_psych_gamma(data.avgdata, 'xreg', 'gamma',...
        'pR_ind', true,...
        'h_ind', true, ...
        'fit_pokedR', fit_pokedR, ...
        'fitLineColor', c_pR, ...
        'dataLineColor', c_pR, ...
        'errorbarColor', c_pR, ...
        'dataFaceColor', c_pR, ...
        'fitLineWidth', 1.5, ...
        'dataMarkerSize', markersize);
    
    lc = pbups_psych_gamma(data.avgdata, 'xreg', 'gamma',...
        'pR_ind', false,...
        'h_ind', true, ...
        'fit_pokedR', fit_pokedR, ...
        'fitLineColor', c_pL, ...
        'dataLineColor', c_pL, ....
        'errorbarColor', c_pL, ...
        'dataFaceColor', c_pL, ...
        'fitLineWidth', 1.5, ...
        'dataMarkerSize', markersize);

end