
function[ll, lr, bias] = return_condpsych_params(data, boot, nboot, seed, p_goright, plotting)

for n = 1:nboot
    
    if ~isempty(p_goright)
        rng('shuffle')
        fit_pokedR = rand(length(p_goright),1) < p_goright;
    else
        fit_pokedR = [];
    end
    
    if boot == 1
        bootseed = seed(n);
    else
        bootseed = [];
    end
    
    prm_rc = pbups_psych_gamma(data.avgdata, 'xreg', 'Delta', 'pR_ind', true, 'h_ind', true, ...
        'fit_pokedR', fit_pokedR, 'bootstrap_seed', bootseed, 'errorbarColor', 'b', ...
        'plotfit', false, 'plotdata', false, 'ploterrorbar', false);
    
    prm_lc = pbups_psych_gamma(data.avgdata, 'xreg', 'Delta', 'pR_ind', false, 'h_ind', true, ...
        'fit_pokedR', fit_pokedR, 'bootstrap_seed', bootseed, ...
        'plotfit', false, 'plotdata', false, 'ploterrorbar', false);
    
    
    % compute PC conditioned psychometric curves
    if plotting
        c_postright = get_linear_cmap([0 164 204]./255, 10);
        c_postleft = get_linear_cmap([233 115 141]./255, 10);
        c_pR = c_postright(1,:);
        c_pL = c_postleft(1,:);
        
        bin_wd = 3;
        range = 36;
        markersize = 12;
        ylabel = {'Fraction choose right', '', ''};
        
%         figure()
        clf;
        rc = pbups_psych_gamma(data.avgdata, 'xreg', 'Delta',...
            'pR_ind', true,...
            'h_ind', true, ...
            'fit_pokedR', fit_pokedR, ...
            'fitLineColor', c_pR, ...
            'dataLineColor', c_pR, ...
            'errorbarColor', c_pR, ...
            'dataFaceColor', c_pR, ...
            'range_delta', range ,...
            'binwd_delta', bin_wd, ...
            'fitLineWidth', 1.5, ...
            'dataMarkerSize', markersize);
        
        lc = pbups_psych_gamma(data.avgdata, 'xreg', 'Delta',...
            'pR_ind', false,...
            'h_ind', true, ...
            'fit_pokedR', fit_pokedR, ...
            'fitLineColor', c_pL, ...
            'dataLineColor', c_pL, ....
            'errorbarColor', c_pL, ...
            'dataFaceColor', c_pL, ...
            'range_delta', range,...
            'binwd_delta', bin_wd, ...
            'fitLineWidth', 1.5, ...
            'dataMarkerSize', markersize);
    end
    
    
    ll(n) = prm_rc.beta(1) - prm_lc.beta(1);
    lr(n) = prm_lc.beta(1) + prm_lc.beta(2) - (prm_rc.beta(1) + prm_rc.beta(2));
    bias(n) = prm_rc.beta(4) - prm_lc.beta(4);
end

end