

savename = "RT_bootstrap_cond_pych_params_lapsemod";
nboots = 500;
plot_bootstraps = false;


[filenames, path_pkgdata] =  get_reaction_time_filenames();
path_fitdata = "~/ondrive/analysisDG/PBups_trialhistory/analyze_reaction_time/saved_fits/";

%%
for i = 1:length(filenames)
    
    display(filenames{i})
    data = load([path_pkgdata, filenames{i}]);
    fitdata = load(strcat(path_fitdata, filenames{i}(1:end-4), "_lapsemod_goright.mat"));
    display(strcat(path_fitdata, filenames{i}(1:end-4), "_lapsemod_goright.mat"));
    
    if plot_bootstraps
        figure();
        ax = gca();
        hold on;
    else
        ax = [];
    end
    tic()
    boot_rc = bootstrap_psych_fit(data.avgdata,...
        'nboots', nboots,...
        'h_ind', 1,...
        'pR_ind', 1,...
        'trial_back', 1,...
        'plot_bootstraps', plot_bootstraps,...
        'ax', ax);
    boot_re = bootstrap_psych_fit(data.avgdata,...
        'nboots', nboots,...
        'h_ind', 0,...
        'pR_ind', 1,...
        'trial_back', 1,...
        'plot_bootstraps', plot_bootstraps,...
        'ax', ax);
    boot_lc = bootstrap_psych_fit(data.avgdata,...
        'nboots', nboots,...
        'h_ind', 1,...
        'pR_ind', 0,...
        'trial_back', 1,...
        'plot_bootstraps', plot_bootstraps,...
        'ax', ax);
    boot_le = bootstrap_psych_fit(data.avgdata,...
        'nboots', nboots,...
        'h_ind', 0,...
        'pR_ind', 0,...
        'trial_back', 1,...
        'plot_bootstraps', plot_bootstraps,...
        'ax', ax);
    toc()
    
    fit_pokedR = fitdata.pred_choices(:, 1)';
    data.avgdata.pokedR = fit_pokedR;
    
    if plot_bootstraps
        figure();
        ax = gca();
        hold on;
    else
        ax = [];
    end
    tic()
    boot_rc_fit = bootstrap_psych_fit(data.avgdata,...
        'nboots', nboots,...
        'h_ind', 1,...
        'pR_ind', 1,...
        'trial_back', 1,...
        'plot_bootstraps',plot_bootstraps,...
        'ax', ax);
    boot_re_fit = bootstrap_psych_fit(data.avgdata,...
        'nboots', nboots,...
        'h_ind', 0,...
        'pR_ind', 1,...
        'trial_back', 1,...
        'plot_bootstraps',plot_bootstraps,...
        'ax', ax);
    boot_lc_fit = bootstrap_psych_fit(data.avgdata,...
        'nboots', nboots,...
        'h_ind', 1,...
        'pR_ind', 0,...
        'trial_back', 1,...
        'plot_bootstraps', plot_bootstraps,...
        'ax', ax);
    boot_le_fit = bootstrap_psych_fit(data.avgdata,...
        'nboots', nboots,...
        'h_ind', 0,...
        'pR_ind', 0,...
        'trial_back', 1,...
        'plot_bootstraps', plot_bootstraps,...
        'ax', ax);
    toc()
    
    % reformat psychometric parameters for plotting param scatters
    rats(i).name  = data.avgdata.ratname{1};
    rats(i).prm.rc = boot_rc;
    rats(i).prm.lc = boot_lc;
    rats(i).prm.re = boot_re;
    rats(i).prm.le = boot_le;
    rats(i).prm_fit.rc = boot_rc_fit;
    rats(i).prm_fit.lc = boot_lc_fit;
    rats(i).prm_fit.re = boot_re_fit;
    rats(i).prm_fit.le = boot_le_fit;
    
end
save(savename, 'rats');